name: Validation Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-prompt:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./scripts/python-scripts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment
        run: pip3 install -r requirements.txt
      - name: Validate prompt
        run: python3 sync.py -t validate
  validate-yaml:
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Use Node.js and cache dependencies
          uses: actions/setup-node@v4
          with:
            node-version: '22.21'
            cache: 'yarn'
        - name: Install dependencies
          run: yarn install --immutable --frozen-lockfile 
        - name: Run Prettier
          run: yarn verify